# Generated by Django 5.1.15 on 2026-03-07 13:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OPERATIVA", "Operativa"),
                            ("AHORRO", "Ahorro"),
                            ("INVERSION", "Inversion"),
                            ("DEPOSITOS", "Depositos"),
                            ("ALTERNATIVOS", "Alternativos"),
                        ],
                        default="OPERATIVA",
                        max_length=15,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("ticker", models.CharField(blank=True, max_length=20, null=True)),
                ("isin", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("STOCK", "Stock"), ("ETF", "ETF"), ("FUND", "Fund"), ("CRYPTO", "Crypto")],
                        default="STOCK",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("current_price", models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                (
                    "price_mode",
                    models.CharField(choices=[("MANUAL", "Manual"), ("AUTO", "Auto")], default="MANUAL", max_length=10),
                ),
                ("issuer_country", models.CharField(blank=True, max_length=2, null=True)),
                ("domicile_country", models.CharField(blank=True, max_length=2, null=True)),
                ("withholding_country", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "price_source",
                    models.CharField(
                        choices=[("YAHOO", "Yahoo Finance"), ("MANUAL", "Manual")], default="YAHOO", max_length=10
                    ),
                ),
                (
                    "price_status",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("ERROR", "Error"), ("NO_TICKER", "No ticker")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("price_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("owner", "isin"), ("owner", "ticker")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("batch_id", models.UUIDField(db_index=True)),
                ("total_market_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("total_unrealized_pnl", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets_portfoliosnapshot_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="PositionSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch_id", models.UUIDField(db_index=True)),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("cost_basis", models.DecimalField(decimal_places=2, max_digits=20)),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("unrealized_pnl", models.DecimalField(decimal_places=2, max_digits=20)),
                ("unrealized_pnl_pct", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_snapshots",
                        to="assets.asset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets_positionsnapshot_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_currency", models.CharField(default="EUR", max_length=3)),
                (
                    "cost_basis_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "First In, First Out"),
                            ("LIFO", "Last In, First Out"),
                            ("WAC", "Weighted Average Cost"),
                        ],
                        default="FIFO",
                        max_length=10,
                    ),
                ),
                (
                    "fiscal_cost_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "First In, First Out"),
                            ("LIFO", "Last In, First Out"),
                            ("WAC", "Weighted Average Cost"),
                        ],
                        default="FIFO",
                        max_length=10,
                    ),
                ),
                (
                    "gift_cost_mode",
                    models.CharField(
                        choices=[("ZERO", "Zero cost"), ("MARKET", "Market price")], default="ZERO", max_length=10
                    ),
                ),
                ("rounding_money", models.PositiveSmallIntegerField(default=2)),
                ("rounding_qty", models.PositiveSmallIntegerField(default=6)),
                (
                    "price_update_interval",
                    models.PositiveIntegerField(
                        default=0, help_text="Auto-update interval in minutes. 0 = disabled (manual only)."
                    ),
                ),
                (
                    "default_price_source",
                    models.CharField(
                        choices=[("YAHOO", "Yahoo Finance"), ("MANUAL", "Manual")], default="YAHOO", max_length=10
                    ),
                ),
                (
                    "snapshot_frequency",
                    models.PositiveIntegerField(
                        default=1440, help_text="Snapshot frequency in minutes. 0 = disabled. Default 1440 (daily)."
                    ),
                ),
                (
                    "data_retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Delete data older than this many days. Null = never delete.",
                        null=True,
                    ),
                ),
                ("purge_portfolio_snapshots", models.BooleanField(default=True)),
                ("purge_position_snapshots", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fintrack_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "settings",
            },
        ),
        migrations.CreateModel(
            name="AccountSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("balance", models.DecimalField(decimal_places=2, max_digits=20)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="assets.account"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("account", "date")},
            },
        ),
    ]
