# Generated by Django 5.1.15 on 2026-03-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_accountsnapshot_idx_accsnapshot_owner_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="positionsnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="positionsnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
