# Generated by Django 5.1.15 on 2026-04-02 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_replace_unique_together_with_constraints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="purge_position_snapshots",
        ),
        migrations.DeleteModel(
            name="PositionSnapshot",
        ),
    ]
