# Generated by Django 5.2 for PortfolioTracker.
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("assets", "0008_india_market_defaults"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="StockAnalysis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("INSUFFICIENT_DATA", "Insufficient data"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VERY_BEARISH", "Very Bearish"),
                            ("BEARISH", "Bearish"),
                            ("NEUTRAL", "Neutral"),
                            ("BULLISH", "Bullish"),
                            ("VERY_BULLISH", "Very Bullish"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("signal_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("data_coverage", models.PositiveSmallIntegerField(default=0)),
                ("summary", models.TextField(blank=True, default="")),
                ("factors", models.JSONField(blank=True, default=dict)),
                ("metrics_snapshot", models.JSONField(blank=True, default=dict)),
                ("bull_case", models.JSONField(blank=True, default=list)),
                ("bear_case", models.JSONField(blank=True, default=list)),
                ("catalysts", models.JSONField(blank=True, default=list)),
                ("risks", models.JSONField(blank=True, default=list)),
                ("citations", models.JSONField(blank=True, default=list)),
                ("data_timestamp", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("gemini_model", models.CharField(blank=True, default="", max_length=80)),
                ("prompt_version", models.CharField(blank=True, default="v1", max_length=32)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stock_analyses", to="assets.asset"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "asset", "-created_at"], name="idx_analysis_owner_asset"),
                    models.Index(fields=["owner", "status", "-created_at"], name="idx_analysis_owner_status"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("signal_score__isnull", True),
                            models.Q(("signal_score__gte", 0), ("signal_score__lte", 100)),
                            _connector="OR",
                        ),
                        name="analysis_signal_score_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("data_coverage__gte", 0), ("data_coverage__lte", 100)),
                        name="analysis_coverage_0_100",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["PENDING", "RUNNING"])),
                        fields=("owner", "asset"),
                        name="unique_active_stock_analysis",
                    ),
                ],
            },
        )
    ]
