# Generated by Django 5.1.15 on 2026-03-15 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_alter_transaction_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dividend",
            name="withholding_rate",
        ),
    ]
