# Generated by Django 6.0.5 on 2026-05-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_loosen_unique_to_include_concept"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="payroll_type",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Mensual"),
                    ("EXTRA", "Paga extra"),
                    ("BONUS", "Bonus / variable"),
                    ("ATRASOS", "Atrasos / regularización"),
                    ("OTHER", "Otro"),
                ],
                default="MONTHLY",
                help_text="Tipo de nómina para análisis: mensual ordinaria, paga extra, bonus/variable, atrasos o cualquier otra. Se infiere del concepto al guardar; el usuario puede ajustarlo manualmente.",
                max_length=16,
            ),
        ),
    ]
