# Generated by Django 6.0.5 on 2026-05-16 12:27

from django.db import migrations, models


def merge_extra_into_bonus(apps, schema_editor):
    """Pagas extra and bonus collapse into a single BONUS bucket. We do
    the data update BEFORE the AlterField so the new choices set doesn't
    contain dangling EXTRA values."""
    Payroll = apps.get_model("payroll", "Payroll")
    Payroll.objects.filter(payroll_type="EXTRA").update(payroll_type="BONUS")


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0005_backfill_payroll_type"),
    ]

    operations = [
        migrations.RunPython(merge_extra_into_bonus, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="payroll",
            name="payroll_type",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Mensual"),
                    ("BONUS", "Bonus / paga extra"),
                    ("ATRASOS", "Atrasos / regularización"),
                    ("OTHER", "Otro"),
                ],
                default="MONTHLY",
                help_text="Tipo de nómina para análisis: mensual ordinaria, paga extra, bonus/variable, atrasos o cualquier otra. Se infiere del concepto al guardar; el usuario puede ajustarlo manualmente.",
                max_length=16,
            ),
        ),
    ]
